### ISSUE TITLE
Issue at start-up

### ISSUE THREAD

**Issue by mtlberri** [tancredi/python-console-snake#21]
Hi,

I just cloned the repo and the program would not start and provide following error:

(base) ➜  python-console-snake git:(master) python snake

Traceback (most recent call last):
                                    File "__main__.py", line 26, in <module>
                                                                                run()
                                                                                       File "__main__.py", line 19, in run
               theme.init()
                             File "/Users/Armellini1/Development/Python/python-console-snake/snake/theme.py", line 14, in init
                   colors_map = get_colors_map()
                                                  File "/Users/Armellini1/Development/Python/python-console-snake/snake/theme.py", line 30, in get_colors_map
                                                  for col in theme['colors'].iteritems():
                                                                                         AttributeError: 'dict' object has no attribute 'iteritems'
                                    %  

Hope that helps.

**Comment by gmaciascorrea** [comment]
Hi mtlberri, 

Please, could you tell me, what operational system are you running the script?
Based on my tests, at windows some functions doesn't work properly. Also, the python version used for this project was python 2.

**Comment by judemont** [comment]
Hello, I have the same error.
My operating system is ubuntu (linux).
My python version is 3.11.1
