### ISSUE TITLE
Can you include requirements.txt ?

### ISSUE THREAD

**Issue by hugotox** [tancredi/python-console-snake#5]
It's not working for me on the mac with python 2.7

```
Traceback (most recent call last):
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals
File "/Users/hpineda/Projects/python-console-snake/snake/__main__.py", line 26, in <module> run()
File "/Users/hpineda/Projects/python-console-snake/snake/__main__.py", line 21, in run gameloop.start()
File "snake/gameloop.py", line 45, in startinit()
File "snake/gameloop.py", line 64, in init graphics.drawGame()
File "snake/graphics.py", line 85, in drawGame drawTile(x, y, theme.get_tile('bg'), theme.get_color('bg'))
File "snake/graphics.py", line 16, in drawTile scre_curses.error: addstr() returned ERR
```

**Comment by tancredi** [comment]
Mmmh that may be a window size  problem, could you try running it with maximised window and let me know if that's the problem?

**Comment by hugotox** [comment]
Yeah, that was it! Thanks

**Comment by tancredi** [comment]
Thanks - I need to fix that eventually
